---
- hosts: nodes
  gather_facts: yes
  roles:
    - role: rhsm-subscription
      rhsm_user: "{{ rhsub_user }}"
      rhsm_password: "{{ rhsub_password }}"
      rhsm_server: "{{vault_rhsub_server}}"
      rhsm_pool: "{{rhsub_pool}}"
      serial: 1
      when: ansible_distribution == "RedHat" and rhsub_user is defined
    - role: rhsm-repos
      openshift_required_repos: ['rhel-7-server-rpms', 'rhel-7-server-extras-rpms', 'rhel-7-fast-datapath-rpms', 'rhel-7-server-ose-3.9-rpms']
